name: CI/CD for Streamlit App

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl libssl-dev python3-dev

      - name: Upgrade pip and install DVC with Google Drive support
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade dvc[gdrive] cryptography pyopenssl

      - name: Create Google Drive credentials file
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS_JSON }}" > gdrive_service_account.json

      - name: Configure DVC remote for Google Drive
        run: |
          dvc remote modify myremote gdrive_service_account_json_file_path gdrive_service_account.json

      - name: Pull DVC data
        run: |
          dvc pull

      - name: Set up MLflow
        run: |
          pip install mlflow
          mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns &

      - name: Train and log models
        run: |
          python src/components/train_and_log_model.py

      - name: Register the best model
        env:
          MLFLOW_TRACKING_URI: "http://127.0.0.1:5000"
        run: |
          python src/register_best_model.py

      - name: Clean up
        run: |
          rm gdrive_service_account.json
