name: MLOps Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dvc-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dvc[gdrive]  # Installer DVC avec support Google Drive
          pip install -r requirements.txt

      - name: Configure DVC
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" > /tmp/google-service-account.json
          dvc remote remove myremote || true  # Supprimer le remote s'il existe déjà
          dvc remote add -d myremote gdrive://$DVC_REMOTE_URL
          dvc remote modify myremote gdrive_service_account /tmp/google-service-account.json

      - name: Pull DVC data
        run: dvc pull

      - name: Reproduce DVC pipeline
        run: dvc repro

      - name: Push DVC data
        run: dvc push
